### ISSUE TITLE
segfault since commit 1e77218

### ISSUE THREAD

**Issue by jschueller** [mgieseki/dvisvgm#58]
Hello,

We use dvisvgm git version in the continuous integration for OpenTURNS and we discovered that yesterday's commit 1e77218 breaks our build despite passing your tests.

Here is a simple test-case:
```
dvisvgm -o a.svg math.dvi
```

You can fetch the file here:
https://gist.github.com/jschueller/bd0717c6396164df9d6e4ee34051c0fb/raw/708adcff67333204973e4d16e5c75d52234ed27d/math.dvi

Here's some output, (I did not succeed running gdb): 
```
pre-processing DVI file (format 2)
processing page 1
  page size: 99.4303pt x 27.5077pt (34.9458mm x 9.66784mm)
  page written to a.svg
1 of 1 page converted in 0.0684741 seconds
*** glibc detected *** dvisvgm: free(): invalid next size (fast): 0x00000000028462f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7db26)[0x7faec7500b26]
dvisvgm[0x44637c]
dvisvgm[0x42a24d]
dvisvgm[0x42a32c]
dvisvgm[0x42a3a9]
dvisvgm[0x436be6]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b5b1)[0x7faec74be5b1]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b635)[0x7faec74be635]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf4)[0x7faec74a4774]
dvisvgm[0x409141]
======= Memory map: ========
00400000-004ef000 r-xp 00000000 08:03 6423167                            /home/schueller/projects/dvisvgm/install/bin/dvisvgm
006ef000-006f0000 r--p 000ef000 08:03 6423167                            /home/schueller/projects/dvisvgm/install/bin/dvisvgm
006f0000-006f1000 rw-p 000f0000 08:03 6423167                            /home/schueller/projects/dvisvgm/install/bin/dvisvgm
006f1000-006f4000 rw-p 00000000 00:00 0 
02520000-02898000 rw-p 00000000 00:00 0                                  [heap]
7faec270e000-7faec2715000 r-xp 00000000 08:01 396610                     /lib/x86_64-linux-gnu/librt-2.15.so
```

**Comment by jschueller** [comment]
Here's finally a traceback:
```
#0  0x00007ffff67590d5 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff675c83b in __GI_abort () at abort.c:91
#2  0x00007ffff679632e in __libc_message (do_abort=2, fmt=0x7ffff68a05d8 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:201
#3  0x00007ffff67a0b26 in malloc_printerr (action=3, str=0x7ffff68a07a0 "free(): invalid next size (fast)", ptr=<optimized out>) at malloc.c:5051
#4  0x000000000044637c in TFM::~TFM() () at /usr/include/c++/4.8/ext/new_allocator.h:110
#5  0x000000000042a24d in TFMFont::~TFMFont() () at Font.cpp:109
#6  0x000000000042a32c in PhysicalFontImpl::~PhysicalFontImpl() () at Font.cpp:479
#7  0x000000000042a3a9 in PhysicalFontImpl::~PhysicalFontImpl() () at Font.cpp:485
#8  0x0000000000436be6 in FontManager::~FontManager() () at FontManager.cpp:38
#9  0x00007ffff675e5b1 in __run_exit_handlers (status=0, listp=0x7ffff6ada688, run_list_atexit=true) at exit.c:78
#10 0x00007ffff675e635 in __GI_exit (status=<optimized out>) at exit.c:100
#11 0x00007ffff6744774 in __libc_start_main (main=0x4069f0 <main>, argc=4, ubp_av=0x7fffffffdf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf18) at libc-start.c:258
#12 0x0000000000409141 in _start ()
```

**Comment by mgieseki** [comment]
Thanks for the bug report. The segfault is triggered by a missing range check in the TFM code. I'm about to fix it.

**Comment by jschueller** [comment]
thanks!
